name: CI
on: [push, pull_request]
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Check style
              run: ./gradlew ktlintCheck

    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Unit tests
              run: ./gradlew testDebugUnitTest

    instrumentation-tests:
        name: Instrumentation tests
        runs-on: macOS-latest
        timeout-minutes: 20
        strategy:
            fail-fast: true
            matrix:
                api-level: [24, 29, 33]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Instrumentation tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  arch: x86
                  script: ./gradlew connectedDebugAndroidTest